/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDataSourcesRouteImport } from './routes/_authenticated/data-sources'
import { Route as AuthenticatedDemandPlanningRouteImport } from './routes/_authenticated/demand-planning'
import { Route as AuthenticatedDistributionRouteImport } from './routes/_authenticated/distribution'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedPurchasingRouteImport } from './routes/_authenticated/purchasing'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated/recommendations'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSupplyPlanningRouteImport } from './routes/_authenticated/supply-planning'
import { Route as AuthenticatedBusinessIndexRouteImport } from './routes/_authenticated/business.index'
import { Route as AuthenticatedBusinessCustomersRouteImport } from './routes/_authenticated/business.customers'
import { Route as AuthenticatedBusinessPipelineRouteImport } from './routes/_authenticated/business.pipeline'
import { Route as AuthenticatedBusinessSignalsRouteImport } from './routes/_authenticated/business.signals'
import { Route as AuthenticatedScenariosIndexRouteImport } from './routes/_authenticated/scenarios.index'
import { Route as AuthenticatedScenariosScenarioIdRouteImport } from './routes/_authenticated/scenarios.$scenarioId'
import { Route as AuthenticatedSkuSkuRouteImport } from './routes/_authenticated/sku.$sku'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDataSourcesRoute =
  AuthenticatedDataSourcesRouteImport.update({
    id: '/data-sources',
    path: '/data-sources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandPlanningRoute =
  AuthenticatedDemandPlanningRouteImport.update({
    id: '/demand-planning',
    path: '/demand-planning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDistributionRoute =
  AuthenticatedDistributionRouteImport.update({
    id: '/distribution',
    path: '/distribution',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasingRoute = AuthenticatedPurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupplyPlanningRoute =
  AuthenticatedSupplyPlanningRouteImport.update({
    id: '/supply-planning',
    path: '/supply-planning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessIndexRoute =
  AuthenticatedBusinessIndexRouteImport.update({
    id: '/business/',
    path: '/business/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessCustomersRoute =
  AuthenticatedBusinessCustomersRouteImport.update({
    id: '/business/customers',
    path: '/business/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessPipelineRoute =
  AuthenticatedBusinessPipelineRouteImport.update({
    id: '/business/pipeline',
    path: '/business/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessSignalsRoute =
  AuthenticatedBusinessSignalsRouteImport.update({
    id: '/business/signals',
    path: '/business/signals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScenariosIndexRoute =
  AuthenticatedScenariosIndexRouteImport.update({
    id: '/scenarios/',
    path: '/scenarios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScenariosScenarioIdRoute =
  AuthenticatedScenariosScenarioIdRouteImport.update({
    id: '/scenarios/$scenarioId',
    path: '/scenarios/$scenarioId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSkuSkuRoute = AuthenticatedSkuSkuRouteImport.update({
  id: '/sku/$sku',
  path: '/sku/$sku',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/data-sources': typeof AuthenticatedDataSourcesRoute
  '/demand-planning': typeof AuthenticatedDemandPlanningRoute
  '/distribution': typeof AuthenticatedDistributionRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/purchasing': typeof AuthenticatedPurchasingRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supply-planning': typeof AuthenticatedSupplyPlanningRoute
  '/business/customers': typeof AuthenticatedBusinessCustomersRoute
  '/business/pipeline': typeof AuthenticatedBusinessPipelineRoute
  '/business/signals': typeof AuthenticatedBusinessSignalsRoute
  '/scenarios/$scenarioId': typeof AuthenticatedScenariosScenarioIdRoute
  '/sku/$sku': typeof AuthenticatedSkuSkuRoute
  '/business/': typeof AuthenticatedBusinessIndexRoute
  '/scenarios/': typeof AuthenticatedScenariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/data-sources': typeof AuthenticatedDataSourcesRoute
  '/demand-planning': typeof AuthenticatedDemandPlanningRoute
  '/distribution': typeof AuthenticatedDistributionRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/purchasing': typeof AuthenticatedPurchasingRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supply-planning': typeof AuthenticatedSupplyPlanningRoute
  '/business/customers': typeof AuthenticatedBusinessCustomersRoute
  '/business/pipeline': typeof AuthenticatedBusinessPipelineRoute
  '/business/signals': typeof AuthenticatedBusinessSignalsRoute
  '/scenarios/$scenarioId': typeof AuthenticatedScenariosScenarioIdRoute
  '/sku/$sku': typeof AuthenticatedSkuSkuRoute
  '/business': typeof AuthenticatedBusinessIndexRoute
  '/scenarios': typeof AuthenticatedScenariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/data-sources': typeof AuthenticatedDataSourcesRoute
  '/_authenticated/demand-planning': typeof AuthenticatedDemandPlanningRoute
  '/_authenticated/distribution': typeof AuthenticatedDistributionRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/purchasing': typeof AuthenticatedPurchasingRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/supply-planning': typeof AuthenticatedSupplyPlanningRoute
  '/_authenticated/business/customers': typeof AuthenticatedBusinessCustomersRoute
  '/_authenticated/business/pipeline': typeof AuthenticatedBusinessPipelineRoute
  '/_authenticated/business/signals': typeof AuthenticatedBusinessSignalsRoute
  '/_authenticated/scenarios/$scenarioId': typeof AuthenticatedScenariosScenarioIdRoute
  '/_authenticated/sku/$sku': typeof AuthenticatedSkuSkuRoute
  '/_authenticated/business/': typeof AuthenticatedBusinessIndexRoute
  '/_authenticated/scenarios/': typeof AuthenticatedScenariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/data-sources'
    | '/demand-planning'
    | '/distribution'
    | '/inventory'
    | '/overview'
    | '/purchasing'
    | '/recommendations'
    | '/settings'
    | '/supply-planning'
    | '/business/customers'
    | '/business/pipeline'
    | '/business/signals'
    | '/scenarios/$scenarioId'
    | '/sku/$sku'
    | '/business/'
    | '/scenarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/data-sources'
    | '/demand-planning'
    | '/distribution'
    | '/inventory'
    | '/overview'
    | '/purchasing'
    | '/recommendations'
    | '/settings'
    | '/supply-planning'
    | '/business/customers'
    | '/business/pipeline'
    | '/business/signals'
    | '/scenarios/$scenarioId'
    | '/sku/$sku'
    | '/business'
    | '/scenarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/data-sources'
    | '/_authenticated/demand-planning'
    | '/_authenticated/distribution'
    | '/_authenticated/inventory'
    | '/_authenticated/overview'
    | '/_authenticated/purchasing'
    | '/_authenticated/recommendations'
    | '/_authenticated/settings'
    | '/_authenticated/supply-planning'
    | '/_authenticated/business/customers'
    | '/_authenticated/business/pipeline'
    | '/_authenticated/business/signals'
    | '/_authenticated/scenarios/$scenarioId'
    | '/_authenticated/sku/$sku'
    | '/_authenticated/business/'
    | '/_authenticated/scenarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/data-sources': {
      id: '/_authenticated/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof AuthenticatedDataSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demand-planning': {
      id: '/_authenticated/demand-planning'
      path: '/demand-planning'
      fullPath: '/demand-planning'
      preLoaderRoute: typeof AuthenticatedDemandPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribution': {
      id: '/_authenticated/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof AuthenticatedDistributionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing': {
      id: '/_authenticated/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof AuthenticatedPurchasingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supply-planning': {
      id: '/_authenticated/supply-planning'
      path: '/supply-planning'
      fullPath: '/supply-planning'
      preLoaderRoute: typeof AuthenticatedSupplyPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/': {
      id: '/_authenticated/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof AuthenticatedBusinessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/customers': {
      id: '/_authenticated/business/customers'
      path: '/business/customers'
      fullPath: '/business/customers'
      preLoaderRoute: typeof AuthenticatedBusinessCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/pipeline': {
      id: '/_authenticated/business/pipeline'
      path: '/business/pipeline'
      fullPath: '/business/pipeline'
      preLoaderRoute: typeof AuthenticatedBusinessPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/signals': {
      id: '/_authenticated/business/signals'
      path: '/business/signals'
      fullPath: '/business/signals'
      preLoaderRoute: typeof AuthenticatedBusinessSignalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenarios/': {
      id: '/_authenticated/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof AuthenticatedScenariosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenarios/$scenarioId': {
      id: '/_authenticated/scenarios/$scenarioId'
      path: '/scenarios/$scenarioId'
      fullPath: '/scenarios/$scenarioId'
      preLoaderRoute: typeof AuthenticatedScenariosScenarioIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sku/$sku': {
      id: '/_authenticated/sku/$sku'
      path: '/sku/$sku'
      fullPath: '/sku/$sku'
      preLoaderRoute: typeof AuthenticatedSkuSkuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDataSourcesRoute: typeof AuthenticatedDataSourcesRoute
  AuthenticatedDemandPlanningRoute: typeof AuthenticatedDemandPlanningRoute
  AuthenticatedDistributionRoute: typeof AuthenticatedDistributionRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPurchasingRoute: typeof AuthenticatedPurchasingRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupplyPlanningRoute: typeof AuthenticatedSupplyPlanningRoute
  AuthenticatedBusinessCustomersRoute: typeof AuthenticatedBusinessCustomersRoute
  AuthenticatedBusinessPipelineRoute: typeof AuthenticatedBusinessPipelineRoute
  AuthenticatedBusinessSignalsRoute: typeof AuthenticatedBusinessSignalsRoute
  AuthenticatedScenariosScenarioIdRoute: typeof AuthenticatedScenariosScenarioIdRoute
  AuthenticatedSkuSkuRoute: typeof AuthenticatedSkuSkuRoute
  AuthenticatedBusinessIndexRoute: typeof AuthenticatedBusinessIndexRoute
  AuthenticatedScenariosIndexRoute: typeof AuthenticatedScenariosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDataSourcesRoute: AuthenticatedDataSourcesRoute,
  AuthenticatedDemandPlanningRoute: AuthenticatedDemandPlanningRoute,
  AuthenticatedDistributionRoute: AuthenticatedDistributionRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPurchasingRoute: AuthenticatedPurchasingRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupplyPlanningRoute: AuthenticatedSupplyPlanningRoute,
  AuthenticatedBusinessCustomersRoute: AuthenticatedBusinessCustomersRoute,
  AuthenticatedBusinessPipelineRoute: AuthenticatedBusinessPipelineRoute,
  AuthenticatedBusinessSignalsRoute: AuthenticatedBusinessSignalsRoute,
  AuthenticatedScenariosScenarioIdRoute: AuthenticatedScenariosScenarioIdRoute,
  AuthenticatedSkuSkuRoute: AuthenticatedSkuSkuRoute,
  AuthenticatedBusinessIndexRoute: AuthenticatedBusinessIndexRoute,
  AuthenticatedScenariosIndexRoute: AuthenticatedScenariosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
